pipeline:
  build:
    image: golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - sleep 10
      - cd todo
      - go get -v
      - go test -v -cover

services:
  database:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

guide:
  name: Go and Mysql
  desc: >
    Example project to demonstrate unit testing Go
    code that depends on a Mysql database
  labels:
    - Go
    - Mysql
